version: '3.3'

services:
  db:
    image: mariadb:10.5.4
    ports:
      - '3306:3306'
    volumes:
      - fpm_dev_data_maria:/var/lib/mysql
    restart: always
    env_file: .env
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    env_file: .env
    networks:
      - wpsite

  web: 
    depends_on: 
      - fpm-dev
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - fpm_dev_web_app:/code
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl
    networks:
      - wpsite

  fpm-dev:
    image: mage7223/fpm-dev:latest
    depends_on: 
      - db
    container_name: fpm-dev
    env_file: .env
    volumes:
      - /path/to/wp/root:/code
      - ~/.ssh:/var/www/.ssh
      - ~/.aws:/var/www/.aws
    networks:
      - wpsite

networks:
  wpsite:
    driver: bridge
volumes:
    fpm_dev_data_maria:
    fpm_dev_web_app: